---
- hosts: Servers
  become: true
  vars_files:
    - ./vars/files.yml
    - ./vars/services.yml

  tasks:
    - name: Update apt repo/cache and upgrade system packages
      apt:
        autoclean: yes
        autoremove: yes
        cache_valid_time: 3600
        force_apt_get: yes 
        update_cache: yes 
        upgrade: yes

    - name: Ensure LDAP related packages are installed.
      apt:
        name:
          - libnss-ldapd
          - sssd 
          - libpam-sss 
          - libnss-sss 
          - sssd-tools 
          - libsss-sudo
        state: present
        autoclean: yes

    - name: Create /etc/netgroup if it does not exist
      copy:
        content: "" 
        dest: /etc/netgroup
        force: no
        group: root
        owner: root
        mode: 0644
      when: not ansible_check_mode

    - name: Copy custom configuration files to servers
      copy:
        src: "{{ item.file_source_path }}"
        dest: "{{ item.file_dest_path }}"
        owner: "{{ item.file_owner }}"
        group: "{{ item.file_group }}"
        mode: "{{ item.file_permission }}"
      loop: "{{ files }}"

    - name: Update CA Trust
      command: update-ca-certificates
      #when: result is changed

    - name: Replace variables in files
      replace:
        path: "{{ item.file_dest_path }}"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.value }}"
        backup: no
      loop: "{{ var_replacements }}"

    - name: Remove problem part of file
      ini_file:
         path: /etc/nslcd.conf
         section: REMOVEME
         state: absent

    - name: Restart services
      service:
        name: "{{ item.service_name }}"
        state: "{{ item.service_restarted_state }}"
      loop: "{{ services }}"

    - name: Verify services started and enabled on boot
      service:
        name: "{{ item.service_name }}"
        state: "{{ item.service_started_state }}"
        enabled: "{{ item.service_enabled }}"
      loop: "{{ services }}"